### ISSUE TITLE
示例不能访问且demo在无法运行，https://docsify.now.sh/

### ISSUE THREAD

**Issue by thinkido** [QingWei-Li/docsify-ssr-demo#7]
启动项目后续显示正常，访问http://localhost:4000后，控制台就报错。

D:\workspace\ssrDemo>npm start

> docsify-ssr-demo@1.0.0 start D:\workspace\ssrDemo
> docsify start . -c ssr.config.js

[SSR] Serving . now.
Listening at http://localhost:4000

TypeError: Cannot read property 'indexOf' of undefined
    at AbstractHistory.parse (D:\workspace\ssrDemo\node_modules\docsify-server-renderer\build.js:267:27)
    at Compiler.compile (D:\workspace\ssrDemo\node_modules\docsify-server-renderer\build.js:813:37)
    at Renderer.<anonymous> (D:\workspace\ssrDemo\node_modules\docsify-server-renderer\build.js:1384:28)
    at Generator.next (<anonymous>)
    at c (D:\workspace\ssrDemo\node_modules\docsify-server-renderer\build.js:16:99)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by brightzoe** [comment]
npm start 在package.json里对应的是`docsify start  .`
在docsify start后面对应的应该是你的docs的路径。

如果把docs/与package.json 放在同一级，你启动项目的cli应该是 `docsify start ./docs` ,修改package.json的对应片段即可。

**Comment by thinkido** [comment]
> npm start 在package.json里对应的是`docsify start .`
> 在docsify start后面对应的应该是你的docs的路径。
> 
> 如果把docs/与package.json 放在同一级，你启动项目的cli应该是 `docsify start ./docs` ,修改package.json的对应片段即可。

可以出个动图或视频吗？这个项目在本地无法运行。你说的docs在文档，和这个项目中都没有提到。
- docs里面又是什么。
- 和ssr.config.js什么关系
- docsify start . -c ssr.config.js 启动后Listening at http://localhost:4000，访问网址获取到的Html里面并没有渲染ssr.html，内容依然是    ，没有被渲染和执行。访问的只是更目录下对应的文件。
```
TypeError: Cannot read property 'indexOf' of undefined
    at AbstractHistory.parse (D:\workspace\docsify_ssr\node_modules\docsify-server-renderer\build.js:297:27)
    at Compiler.compile (D:\workspace\docsify_ssr\node_modules\docsify-server-renderer\build.js:857:37)
    at Renderer.<anonymous> (D:\workspace\docsify_ssr\node_modules\docsify-server-renderer\build.js:1431:28)
    at Generator.next (<anonymous>)
    at c (D:\workspace\docsify_ssr\node_modules\docsify-server-renderer\build.js:16:99)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by thinkido** [comment]
初步判断是一个bug：
line857: this$1.router.parse().file;
Line:294 
```
AbstractHistory.prototype.parse = function parse (path) {
    var query = '';

    var queryIndex = path.indexOf('?');
```
Line1327: this.router = new AbstractHistory(config);
第一行中没有传递参数，

**Comment by thinkido** [comment]
在文档 [docsify/ssr.md at develop · docsifyjs/docsify](https://github.com/docsifyjs/docsify/blob/develop/docs/ssr.md) 中有说明，但是这个demo项目是无法运行的。
docsify源码中执行npm run serve:ssr 和 npm run dev:ssr 也不行，

**Comment by thinkido** [comment]
github中搜索其他人的代码，找到了可以直接运行的demo。
[workspace/server.js at 8528d0fae03e74a94d447212d328d3dd8579acc6 · zhaobohao/workspace](https://github.com/zhaobohao/workspace/blob/8528d0fae03e74a94d447212d328d3dd8579acc6/icsopenapi/develop-doc/server.js)

**Comment by thinkido** [comment]
<body>
  
  
</body>
从其他人的代码中看到只是简单的把json字符添加到htrml，不是真实的html。官方demo 链接访问不了，如果不是渲染成seo可以爬取的 md ->text div -dom。那也就不用耗费几个小时尝试跑通demo了。

**Comment by ruanqizhen** [comment]
应该把这个demo删掉，否则浪费大家时间。
